### ISSUE TITLE
Release_LTCG

### ISSUE THREAD

**Issue by jogolden** [cloverleafswag3/testdev#1]
Release just put the xex on your test kit and run it!
You will see if it worked just by looking at the dev dash thingy!
http://www.mediafire.com/download/1wb0358b3e5adc6/testdev.zip

**Comment by reminon** [comment]
won't launch the xex  on 21256.12.

**Comment by jogolden** [comment]
recompile, it should work no problem

**Comment by reminon** [comment]
still not launching...even tried different recoveries..is there a way to manually place the xbdm.xex?

**Comment by jogolden** [comment]
im the flash, build a custom devkit image with xebuild it will work. but if you cant get this working then good luck reconfiguring xebuild.

**Comment by reminon** [comment]
I didn't know xebuild could build images for test kits

**Comment by jogolden** [comment]
I know it can for devkits, and it should for testkits, just have to configure correctly.
Its probably not worth it, all you need is to write xbdm.xex in the flash.

**Comment by reminon** [comment]
I have flash access...could I just drop the file in?

**Comment by jogolden** [comment]
Yea ofc your probably using xexmenu right? Im almost certain it wont work but go ahead try it.
You have to write the new xbdm.xex over in chunks to the flash.

**Comment by reminon** [comment]
ok so after a few recompiles  I got a working xex...thank you so much for this..is there a way to add xdrpc?

**Comment by jogolden** [comment]
xdrpc should work
